import { useState } from 'react';
import { Sheet } from './Sheet';
import { store, useTripState } from '../state/store';
import type { Card } from '../state/schema';

export function CardSheet({ id, onClose }: { id?: string; onClose: () => void }) {
  const state = useTripState(); const existing = state.cards.find(card => card.id === id);
  const [draft, setDraft] = useState<Card>(existing ?? { id: crypto.randomUUID(), type: 'visa', nick: '', bank: '', network: 'Visa', holder: '', last4: '', markup: 3, fee: 0, cur: 'IDR', limit: 0 });
  return <Sheet open onClose={onClose} title={existing ? 'Edit card or cash' : 'Add card or cash'}><p className="hint">Only the last 4 digits are stored. Never enter a full number or CVV.</p><label className="f"><span>Type</span><select value={draft.type} onChange={e => setDraft({ ...draft, type: e.target.value })}><option value="visa">Visa</option><option value="mastercard">Mastercard</option><option value="amex">Amex</option><option value="cash">Cash</option></select></label><label className="f"><span>Nickname</span><input value={draft.nick} onChange={e => setDraft({ ...draft, nick: e.target.value })} /></label><label className="f"><span>Bank</span><input value={draft.bank ?? ''} onChange={e => setDraft({ ...draft, bank: e.target.value })} /></label>{draft.type !== 'cash' && <label className="f"><span>Last 4 digits only</span><input inputMode="numeric" maxLength={4} value={draft.last4 ?? ''} onChange={e => setDraft({ ...draft, last4: e.target.value.replace(/\D/g, '').slice(-4) })} /></label>}<label className="f"><span>{draft.type === 'cash' ? 'Cash carried' : 'Limit'}</span><input type="number" value={draft.limit ?? 0} onChange={e => setDraft({ ...draft, limit: Number(e.target.value) })} /></label>{draft.type === 'cash' && <label className="f"><span>Currency</span><select value={draft.cur ?? 'USD'} onChange={e => setDraft({ ...draft, cur: e.target.value })}><option>USD</option><option>CAD</option><option>IDR</option></select></label>}<div className="grid2"><label className="f"><span>FX markup %</span><input type="number" step="0.1" value={draft.markup ?? 0} onChange={e => setDraft({ ...draft, markup: Number(e.target.value) })} /></label><label className="f"><span>Flat fee %</span><input type="number" step="0.1" value={draft.fee ?? 0} onChange={e => setDraft({ ...draft, fee: Number(e.target.value) })} /></label></div><button className="btn" disabled={!draft.nick} onClick={() => { store.mutate('cards', draft.id, s => { const i = s.cards.findIndex(card => card.id === draft.id); if (i >= 0) s.cards[i] = draft; else s.cards.push(draft); }); onClose(); }}>Save card</button></Sheet>;
}
