import { useEffect, useState } from 'react';
import { Sheet } from './Sheet';
import { clearSyncConfig, loadSyncConfig, saveSyncConfig, type SyncConfig } from '../state/persist';
import { store, useTripState } from '../state/store';

const BUILD = '2026.08.07-4';
export function SettingsSheet({ open, onClose }: { open: boolean; onClose: () => void }) {
  const state = useTripState(); const [config, setConfig] = useState<SyncConfig>(loadSyncConfig() ?? { owner: '', repo: 'honeymoon-data', branch: 'main', token: '', device: '' }); const [storage, setStorage] = useState<string>('checking…');
  useEffect(() => { if (!open || !navigator.storage?.estimate) return; void navigator.storage.estimate().then(e => setStorage(`${Math.round((e.usage ?? 0) / 1024 / 1024 * 10) / 10} MB used of ${Math.round((e.quota ?? 0) / 1024 / 1024)} MB`)); }, [open]);
  const download = () => { const payload = { bookings: state.bookings, done: state.done, items: state.items, notes: state.notes, exportedAt: new Date().toISOString() }; const url = URL.createObjectURL(new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = 'larch-canyon-backup.json'; a.click(); URL.revokeObjectURL(url); };
  return <Sheet open={open} onClose={onClose} title="Settings"><section><div className="eyebrow">GitHub sync</div><p className="hint">Both phones can share through a <b>private</b> data repository. Local saves work without signal.</p><div className="alert"><b>Use a private repo for data</b>Bookings, addresses, confirmation numbers, and photos go here. The app repository remains public; the data repository must not be.</div>{(['owner', 'repo', 'branch', 'device'] as const).map(field => <label className="f" key={field}><span>{field}</span><input value={config[field]} onChange={e => setConfig({ ...config, [field]: e.target.value })} /></label>)}<label className="f"><span>Fine-grained access token</span><input type="password" value={config.token} onChange={e => setConfig({ ...config, token: e.target.value })} /></label><button className="btn" disabled={import.meta.env.VITE_SYNC_ENABLED !== '1'} onClick={() => { saveSyncConfig(config); store.setConfig(config); store.boot(); }}>Connect and sync</button>{import.meta.env.VITE_SYNC_ENABLED !== '1' && <p className="hint">Sync is disabled in this foundation build and will be enabled only at Plan 3 cutover.</p>}</section><section className="sect-h"><h2>Backup</h2></section><button className="btn ghost" onClick={download}>Download local backup</button><section className="sect-h"><h2>Storage</h2></section><p className="hint">{storage}</p><button className="btn ghost" onClick={() => void navigator.storage?.persist?.()}>Keep storage persistent</button><section className="sect-h"><h2>App</h2></section><p className="hint">Build {BUILD}</p><button className="btn ghost" onClick={() => window.location.reload()}>Hard refresh</button><button className="btn ghost" onClick={() => { clearSyncConfig(); store.setConfig(null); setConfig({ owner: '', repo: 'honeymoon-data', branch: 'main', token: '', device: '' }); }}>Clear sync setup</button></Sheet>;
}
