import { useMemo, useState } from 'react';
import { useTripState } from '../state/store';
import { cardRate, FX } from '../lib/fx';
import { cheapestCard, headroom, spendForCard, totalSpendInIdr } from '../lib/budget';
import { RateStrip } from '../components/RateStrip';
import { CardSheet } from '../components/CardSheet';
import { SpendSheet } from '../components/SpendSheet';

export function Budget() {
  const state = useTripState(); const [sheet, setSheet] = useState<'card' | 'spend' | null>(null); const [cardId, setCardId] = useState<string>();
  const cheapest = useMemo(() => cheapestCard(state.cards), [state.cards]);
  const total = totalSpendInIdr(state.spend, state.cards);
  return <section><div className="route-heading"><div className="eyebrow">Road money</div><h1>Budget</h1><p className="hint">Track what has gone out, what is left, and which card is cheapest abroad.</p></div><RateStrip /><div className="card pad"><div className="eyebrow">Logged spend</div><h2>IDR {Math.round(total).toLocaleString()}</h2><p className="hint">{state.spend.length} entries · cards never store full numbers.</p></div><div className="sect-h"><h2>Cards &amp; cash</h2><button className="btn ghost sm" onClick={() => { setCardId(undefined); setSheet('card'); }}>Add</button></div>{state.cards.length === 0 && <div className="empty card"><h3>No cards yet</h3><p>Add a card or cash reserve to see effective rates and headroom.</p></div>}{state.cards.map(card => { const summary = headroom(card, state.spend); const spent = spendForCard(state.spend, card); const warning = card.type !== 'cash' && summary.percent >= 85; return <article className="card pad money-card" key={card.id}><div className="row"><h3>{card.nick}</h3><span className="tag">{card.type}</span><span className="sp" /><button className="btn ghost sm" onClick={() => { setCardId(card.id); setSheet('card'); }}>Edit</button></div><p className="hint">Effective rate: IDR {Math.round(cardRate(card, 'USD')).toLocaleString()} / USD</p><div className="kv"><span className="k">Spent (IDR)</span><span className="v">{Math.round(summary.spent).toLocaleString()}</span></div><div className="kv"><span className="k">{card.type === 'cash' ? 'Cash remaining' : 'Headroom'}</span><span className="v">{summary.remaining.toLocaleString()} · {Math.round(summary.percent)}%</span></div><div className="meter"><i className={warning ? 'hi' : ''} style={{ width: `${Math.min(100, summary.percent)}%` }} /></div>{warning && <div className="alert"><b>Near limit</b>More than 85% of this card’s limit is logged.</div>}</article>; })}{cheapest && state.cards.length > 1 && <div className="alert ok"><b>Cheapest card to spend on: {cheapest.nick}</b>Lowest entered markup at the current mid-market rate.</div>}<div className="sect-h"><h2>Spend log</h2><button className="btn" onClick={() => setSheet('spend')}>Add spend</button></div>{state.spend.map(entry => <div className="kv card pad" key={entry.id}><span className="k">{entry.date} · {entry.what}</span><span className="v">{entry.cur} {entry.amt}</span></div>)}{sheet === 'card' && <CardSheet id={cardId} onClose={() => setSheet(null)} />}{sheet === 'spend' && <SpendSheet onClose={() => setSheet(null)} />}</section>;
}
